/* eslint-env node */
module.exports = {
    extends: "eslint:recommended",
    parser: "babel-eslint",
    env: {
        browser: true,
        es6: true,
        commonjs: true,
    },
    plugins: ["react", "import"],
    rules: {
        "array-bracket-spacing": [2, "never"],
        "arrow-body-style": [2, "as-needed", { requireReturnForObjectLiteral: false }],
        "arrow-parens": 2,
        "arrow-spacing": [2, { before: true, after: true }],
        "block-spacing": [2, "always"],
        "brace-style": [2, "1tbs", { allowSingleLine: true }],
        camelcase: 2,
        "comma-dangle": [2, "always-multiline"],
        "comma-spacing": 2,
        "comma-style": [2, "last"],
        "computed-property-spacing": [2, "never"],
        "consistent-return": 0,
        "consistent-this": [2, "self"],
        curly: [2, "all"],
        "dot-notation": [2, { allowPattern: "^[a-z]+(_[a-z]+)+$" }],
        "eol-last": 2,
        eqeqeq: [2, "smart"],
        "func-call-spacing": [2, "never"],
        "func-names": 0,
        "func-style": 0,
        "import/default": 2,
        "import/export": 2,
        "import/imports-first": 2,
        "import/named": 2,
        "import/namespace": 2,
        "import/newline-after-import": 2,
        "import/no-absolute-path": 2,
        "import/no-amd": 2,
        "import/no-commonjs": 2,
        "import/no-extraneous-dependencies": 2,
        "import/no-mutable-exports": 2,
        "import/no-named-as-default": 2,
        "import/no-named-as-default-member": 2,
        "import/no-nodejs-modules": 2,
        "import/no-unresolved": 2,
        "import/prefer-default-export": 2,
        indent: [2, 4],
        "jsx-quotes": [2, "prefer-double"],
        "key-spacing": [2, { beforeColon: false, afterColon: true }],
        "keyword-spacing": 2,
        "new-cap": [2, { capIsNew: false, newIsCap: true }],
        "new-parens": 2,
        "no-alert": 2,
        "no-array-constructor": 2,
        "no-caller": 2,
        "no-catch-shadow": 2,
        "no-const-assign": 2,
        "no-duplicate-imports": 2,
        "no-else-return": 2,
        "no-eval": 2,
        "no-extend-native": 2,
        "no-extra-bind": 2,
        "no-extra-parens": [2, "functions"],
        "no-implied-eval": 2,
        "no-iterator": 2,
        "no-label-var": 2,
        "no-labels": 2,
        "no-lone-blocks": 2,
        "no-loop-func": 2,
        "no-multi-spaces": 2,
        "no-multi-str": 2,
        "no-native-reassign": 2,
        "no-new-func": 2,
        "no-new-object": 2,
        "no-new": 2,
        "no-octal-escape": 2,
        "no-process-exit": 2,
        "no-proto": 2,
        "no-return-assign": 2,
        "no-script-url": 2,
        "no-sequences": 2,
        "no-shadow-restricted-names": 2,
        "no-shadow": 2,
        "no-spaced-func": 2,
        "no-trailing-spaces": 2,
        "no-undef-init": 2,
        "no-underscore-dangle": 0,
        "no-unneeded-ternary": 2,
        "no-unused-expressions": 2,
        "no-use-before-define": [2, "nofunc"],
        "no-useless-computed-key": 2,
        "no-useless-constructor": 2,
        "no-useless-rename": 2,
        "no-var": 2,
        "no-with": 2,
        "object-curly-spacing": [2, "always", { objectsInObjects: false }],
        "object-shorthand": 2,
        "one-var": [2, "never"],
        "operator-linebreak": [2, "after"],
        "padded-blocks": [2, "never"],
        "prefer-const": 2,
        "prefer-rest-params": 2,
        "prefer-spread": 2,
        "prefer-template": 2,
        "quote-props": [2, "as-needed", { keywords: false, unnecessary: true, numbers: false }],
        quotes: [2, "double", "avoid-escape"],
        "react/jsx-boolean-value": [2, "always"],
        "react/jsx-closing-bracket-location": [2, "tag-aligned"],
        "react/jsx-curly-spacing": [2, "never"],
        "react/jsx-equals-spacing": [2, "never"],
        "react/jsx-first-prop-new-line": [2, "multiline"],
        "react/jsx-handler-names": [
            2,
            {
                eventHandlerPrefix: "handle",
                eventHandlerPropPrefix: "on",
            },
        ],
        "react/jsx-indent": [2, 4],
        "react/jsx-indent-props": [2, 4],
        "react/jsx-key": 2,
        "react/jsx-no-bind": [
            2,
            {
                ignoreRefs: true,
                allowArrowFunctions: false,
                allowBind: false,
            },
        ],
        "react/jsx-no-comment-textnodes": 2,
        "react/jsx-no-duplicate-props": 2,
        "react/jsx-no-undef": 2,
        "react/jsx-pascal-case": 2,
        "react/jsx-space-before-closing": [2, "always"],
        "react/jsx-uses-react": 2,
        "react/jsx-uses-vars": 2,
        "react/jsx-wrap-multilines": 2,
        "react/no-danger": 2,
        "react/no-danger-with-children": 2,
        "react/no-deprecated": 2,
        "react/no-did-mount-set-state": 2,
        "react/no-did-update-set-state": 2,
        "react/no-direct-mutation-state": 2,
        "react/no-find-dom-node": 2,
        "react/no-is-mounted": 2,
        "react/no-multi-comp": [2, { ignoreStateless: true }],
        "react/no-render-return-value": 2,
        "react/no-string-refs": 2,
        "react/no-unknown-property": 2,
        "react/no-unused-prop-types": [2, { skipShapeProps: true }],
        "react/prefer-es6-class": [2, "never"], // soon to change once codemode has been run!
        "react/prop-types": 2,
        "react/react-in-jsx-scope": 2,
        "react/require-optimization": 2,
        "react/require-render-return": 2,
        "react/self-closing-comp": 2,
        "react/sort-comp": [
            2,
            {
                order: [
                    "static-methods",
                    "lifecycle",
                    "/^getDefaultProps$/",
                    "/^getInitialState$/",
                    "/^handle.+$/",
                    "everything-else",
                    "/^get[a-zA-Z]*Styles$/",
                    "/^render.+$/",
                    "render",
                ],
                groups: {
                    lifecycle: [
                        // We prefer mixins before propTypes
                        "displayName",
                        "mixins",
                        "propTypes",
                        "contextTypes",
                        "childContextTypes",
                        "statics",
                        "defaultProps",
                        "constructor",
                        "getDefaultProps",
                        "getInitialState",
                        "state",
                        "getChildContext",
                        "componentWillMount",
                        "componentDidMount",
                        "componentWillReceiveProps",
                        "shouldComponentUpdate",
                        "componentWillUpdate",
                        "componentDidUpdate",
                        "componentWillUnmount",
                    ],
                },
            },
        ],
        "react/style-prop-object": 2,
        "rest-spread-spacing": [2, "never"],
        "semi-spacing": [2, { before: false, after: true }],
        semi: [2, "always"],
        "space-before-blocks": [2, "always"],
        "space-before-function-paren": [2, "never"],
        "space-in-parens": [2, "never"],
        "space-infix-ops": [2, { int32Hint: false }],
        "space-unary-ops": [2, { words: true, nonwords: false }],
        "spaced-comment": 2,
        strict: [2, "never"],
        "template-curly-spacing": [2, "never"],
        yoda: [2, "never"],
    },
};
